version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: etherpin
      POSTGRES_PASSWORD: etherpin
      POSTGRES_DB: etherpin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 10
  migrator:
    build:
      context: .
      target: migrator
    develop:
      watch:
          - action: rebuild
            path: ./requirements*.txt
    environment:
      ETHERPIN_DJANGO_SECRET: "mysupersecretsecret"
      ETHERPIN_DB_DEFAULT: "postgres://etherpin:etherpin@db/etherpin"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: .
      target: development
    develop:
      watch:
          - action: rebuild
            path: ./requirements*.txt
    environment:
      ETHERPIN_DJANGO_SECRET: "mysupersecretsecret"
      ETHERPIN_DB_DEFAULT: "postgres://etherpin:etherpin@db/etherpin"
    ports:
      - "8000:8000"
    volumes:
      - .:/srv
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
