version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: etherpin
      POSTGRES_PASSWORD: etherpin
      POSTGRES_DB: etherpin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 10
  migrator:
    build:
      context: .
      target: migrator
      cache_from:
        - licorneutc/etherpin:migrator-latest
    develop:
      watch:
          - action: rebuild
            path: ./requirements*.txt
    environment:
      INFISICAL_TOKEN: "st.6527ddee79ae49ee9dfc160f.d555a31eb1563f3bf1ee72a6f001ddb9.af4f02caa62ef00559b5d96f588103c7"  # db-dev
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: .
      target: development
      cache_from:
        - licorneutc/etherpin:development-latest
    develop:
      watch:
          - action: rebuild
            path: ./requirements*.txt
    environment:
      INFISICAL_TOKEN: "st.6527de0320be947d92e91c7d.922811965d60fd55f66f281377c0dc9a.4b65b89fb8fd8e5d6cc1b82ba57764b3"  # web-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/srv
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
