name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-development:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker development image
      run: docker build . --file Dockerfile --tag etherpin-development:$(date +%s)
  build-migrator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker migrator image
      run: docker build . --file Dockerfile --tag etherpin-migrator:$(date +%s)
  build-final:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker final image
      run: docker build . --file Dockerfile --tag etherpin:$(date +%s)
